"""tmux frame construction and repair."""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from . import PROTOCOL_VERSION, SCHEMA_VERSION, __version__
from .config import DEFAULT_KEYS, _editor_argv as resolve_editor_argv
from .errors import HiveIdeError, UsageError
from .layout import IdeLayout
from .python_cmd import PythonCommand
from .source import inspect_interpreter
from .store import StateStore, utc_now


class Frame:
    PANE_ROLES = ("sidebar", "agent", "plan")
    SIDEBAR_W = IdeLayout.SIDEBAR_W
    PLAN_W = IdeLayout.PLAN_W
    AGENT_PREF = IdeLayout.AGENT_PREF
    SIDEBAR_ZOOM_MAX = IdeLayout.mobile_threshold()
    DEPENDED_OPTIONS = ("mouse", "prefix", "focus-events")
    USER_CONFS = (".tmux.conf", ".config/tmux/tmux.conf")
    PLUS_LINE_EDITORS = {
        "micro",
        "vim",
        "nvim",
        "vi",
        "view",
        "gvim",
        "nano",
        "emacs",
        "emacsclient",
    }
    PLAN_PANE_READONLY_FLAGS = {
        "micro": ["-readonly", "true"],
        "vim": ["-R"],
        "nvim": ["-R"],
        "vi": ["-R"],
        "gvim": ["-R"],
    }
    INTERACTIVE_ENV_UNSET = ("NO_COLOR",)
    SHELL_COMMANDS = {"sh", "bash", "fish", "zsh"}

    def __init__(self, store: StateStore, *, socket: str | None = None):
        self.store = store
        self.settings = store.read_path(store.config_snapshot_path()) or {}
        saved_tmux = self.settings.get("tmux") or {}
        self.socket = (
            socket
            or saved_tmux.get("socket")
            or f"hive-ide-{store.workspace_hash[:8]}"
        )
        self.target = f"hive-ide-{store.workspace_hash[:8]}"
        self.python = sys.executable

    def _ide_conf(self) -> Path | None:
        """Copy the user's tmux config while disabling continuum for this server."""
        source = next(
            (
                path
                for relative in self.USER_CONFS
                if (path := Path.home() / relative).is_file()
            ),
            None,
        )
        if source is None:
            return None
        output = self.store.workspace_dir / "ide.conf"
        try:
            original = source.read_text(encoding="utf-8").splitlines()
        except OSError as exc:
            raise UsageError(f"Could not read tmux config {source}: {exc}") from exc
        lines = [
            f"# Generated by hive-ide from {source}; do not edit.",
            "# tmux-continuum restore and autosave are disabled for this server only.",
            "",
        ]
        save_disabled = False
        for line in original:
            if re.match(r"^\s*set\b.*@continuum-restore", line):
                lines.extend(
                    [f"# [hive-ide] was: {line.strip()}", "set -g @continuum-restore 'off'"]
                )
            elif re.match(r"^\s*set\b.*@continuum-save-interval", line):
                lines.append(f"# [hive-ide] was: {line.strip()}")
            else:
                if re.match(r"^\s*run\b.*tpm", line) and not save_disabled:
                    lines.append(
                        "set -g @continuum-save-interval '0' # hive-ide never autosaves"
                    )
                    save_disabled = True
                lines.append(line)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return output

    def tmux(
        self, args: list[str], *, clean_start: bool = False
    ) -> subprocess.CompletedProcess[str]:
        generated = self._ide_conf() if clean_start else None
        config = ["-f", str(generated)] if generated else []
        return subprocess.run(
            ["tmux", "-L", self.socket, *config, *args],
            capture_output=True,
            text=True,
        )

    def require_tmux(self) -> None:
        if shutil.which("tmux") is None:
            raise UsageError("tmux is required but was not found on PATH.")
        handshake = subprocess.run(
            PythonCommand.cli_argv(["version"], python=self.python),
            capture_output=True,
            text=True,
        )
        if handshake.returncode != 0:
            raise UsageError(
                "The selected Python interpreter cannot import hive_ide. Install the "
                "package into that environment."
            )

    def exists(self) -> bool:
        return self.tmux(["has-session", "-t", self.target]).returncode == 0

    def windows(self) -> dict[str, str]:
        if not self.exists():
            return {}
        result = self.tmux(
            [
                "list-windows",
                "-t",
                self.target,
                "-F",
                "#{@hive_ide_session_id}\t#{window_id}",
            ]
        )
        if result.returncode != 0:
            return {}
        rows: dict[str, str] = {}
        for line in result.stdout.splitlines():
            session_id, _, window_id = line.partition("\t")
            if session_id:
                rows[session_id] = window_id
        return rows

    def role_panes(self, session_id: str) -> dict[str, str]:
        window_id = self.windows().get(session_id)
        if not window_id:
            return {}
        return self._role_panes_in_window(window_id)

    def pane_hive_ide_env(self, pane_id: str) -> dict[str, str]:
        pid = self._pane_pid(pane_id)
        if pid is None:
            return {}
        for candidate in reversed(self._process_tree(pid)):
            env = self._process_env(candidate)
            if any(key.startswith("HIVE_IDE_") for key in env):
                return {
                    key: value
                    for key, value in env.items()
                    if key.startswith("HIVE_IDE_")
                }
        return {}

    def _pane_pid(self, pane_id: str) -> int | None:
        result = self.tmux(["display-message", "-p", "-t", pane_id, "#{pane_pid}"])
        if result.returncode != 0:
            return None
        value = result.stdout.strip()
        return int(value) if value.isdigit() else None

    @staticmethod
    def _process_tree(pid: int) -> list[int]:
        seen: set[int] = set()
        ordered: list[int] = []
        stack = [pid]
        while stack:
            current = stack.pop()
            if current in seen:
                continue
            seen.add(current)
            ordered.append(current)
            children = Path(f"/proc/{current}/task/{current}/children")
            try:
                child_ids = [
                    int(item)
                    for item in children.read_text(encoding="utf-8").split()
                    if item.isdigit()
                ]
            except OSError:
                child_ids = []
            stack.extend(child_ids)
        return ordered

    @staticmethod
    def _process_env(pid: int) -> dict[str, str]:
        try:
            raw = Path(f"/proc/{pid}/environ").read_bytes()
        except OSError:
            return {}
        env: dict[str, str] = {}
        for item in raw.split(b"\0"):
            if b"=" not in item:
                continue
            key, value = item.split(b"=", 1)
            try:
                env[key.decode("utf-8")] = value.decode("utf-8", errors="replace")
            except UnicodeDecodeError:
                continue
        return env

    def _role_panes_in_window(self, window_id: str) -> dict[str, str]:
        result = self.tmux(
            [
                "list-panes",
                "-t",
                window_id,
                "-F",
                "#{@hive_ide_pane}\t#{pane_id}",
            ]
        )
        if result.returncode != 0:
            return {}
        return {
            role: pane_id
            for line in result.stdout.splitlines()
            for role, _, pane_id in [line.partition("\t")]
            if role and pane_id
        }

    def _pane_indices(self, window_id: str) -> dict[int, str]:
        result = self.tmux(
            [
                "list-panes",
                "-t",
                window_id,
                "-F",
                "#{pane_index}\t#{pane_id}",
            ]
        )
        if result.returncode != 0:
            return {}
        rows: dict[int, str] = {}
        for line in result.stdout.splitlines():
            index, _, pane_id = line.partition("\t")
            if index.isdigit() and pane_id:
                rows[int(index)] = pane_id
        return rows

    def _pane_rows(self, window_id: str) -> list[tuple[int, str, str]]:
        result = self.tmux(
            [
                "list-panes",
                "-t",
                window_id,
                "-F",
                "#{pane_index}\t#{pane_id}\t#{@hive_ide_pane}",
            ]
        )
        if result.returncode != 0:
            return []
        rows: list[tuple[int, str, str]] = []
        for line in result.stdout.splitlines():
            index, pane_id, role = (
                line.split("\t") if line.count("\t") == 2 else ("", "", "")
            )
            if index.isdigit() and pane_id:
                rows.append((int(index), pane_id, role))
        return rows

    def _order_role_panes(self, window_id: str) -> dict[str, str]:
        rows = self._pane_rows(window_id)
        roles = {role: pane_id for _, pane_id, role in rows if role}
        if set(self.PANE_ROLES) - set(roles):
            return roles
        for _ in range(len(self.PANE_ROLES)):
            changed = False
            rows = self._pane_rows(window_id)
            by_index = {index: (pane_id, role) for index, pane_id, role in rows}
            by_role = {role: index for index, _, role in rows if role}
            for index, role in enumerate(self.PANE_ROLES):
                current = by_index.get(index)
                if current and current[1] == role:
                    continue
                source_index = by_role.get(role)
                if source_index is None:
                    continue
                self.tmux(
                    [
                        "swap-pane",
                        "-d",
                        "-s",
                        f"{window_id}.{source_index}",
                        "-t",
                        f"{window_id}.{index}",
                    ]
                )
                changed = True
                break
            if not changed:
                break
        return self._role_panes_in_window(window_id)

    def _module(
        self, module: str, args: list[str], *, interpreter: str | None = None
    ) -> str:
        return PythonCommand.module_command(
            module, args, python=interpreter or self.python
        )

    def _environment(self, record: dict[str, Any]) -> list[str]:
        source = record.get("source") or {}
        env = [
            "-e",
            f"HIVE_IDE_PROTOCOL_VERSION={PROTOCOL_VERSION}",
            "-e",
            f"HIVE_IDE_VERSION={__version__}",
            "-e",
            f"HIVE_IDE_STATE_HOME={self.store.home}",
            "-e",
            f"HIVE_IDE_WORKSPACE_KEY={self.store.workspace_key}",
            "-e",
            f"HIVE_IDE_TMUX_SOCKET={self.socket}",
            "-e",
            f"HIVE_IDE_SESSION_ID={record['id']}",
            "-e",
            f"HIVE_IDE_SESSION={record['name']}",
            "-e",
            f"HIVE_IDE_SOURCE={source.get('kind') or 'stable'}",
        ]
        hive = (record.get("host") or {}).get("hive") or {}
        repo = hive.get("repo")
        if isinstance(repo, str) and repo:
            env.extend(["-e", f"HIVE_IDE_REPO={repo}"])
        legacy_skill = Path(self.store.workspace_key) / ".skills" / "hive-ide"
        if legacy_skill.is_dir():
            env.extend(["-e", f"HIVE_IDE_SKILL_DIR={legacy_skill}"])
        handoff = record.get("handoff")
        if isinstance(handoff, dict) and handoff:
            payload = json.dumps(handoff, separators=(",", ":"), sort_keys=True)
            env.extend(["-e", f"HIVE_IDE_HANDOFF_JSON={payload}"])
        return env

    def _refresh_source_if_needed(
        self, record: dict[str, Any], interpreter: str
    ) -> None:
        handshake = inspect_interpreter(interpreter)
        source = record.get("source") or {}
        if handshake["package_version"] == source.get("version"):
            return
        if (
            source.get("kind") == "stable"
            and handshake.get("protocol_version") == PROTOCOL_VERSION
            and handshake.get("schema_version") == SCHEMA_VERSION
        ):
            record["source"] = {**source, "version": handshake["package_version"]}
            self.store.write("sessions", record["id"], record)
            return
        raise UsageError(
            f"Session source version changed at {interpreter}; run source-set again."
        )

    def _sidebar_command(self, record: dict[str, Any]) -> str:
        command = self._module(
            "sidebar",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--session-id",
                record["id"],
                "--tmux-socket",
                self.socket,
            ],
            interpreter=self._record_python(record),
        )
        visible = (
            'tmux display-message -p -t "$TMUX_PANE" "#{window_active}" '
            "2>/dev/null | grep -qx 1"
        )
        return self._interactive_command(
            f"while :; do if {visible}; then {command}; sleep 1; "
            "else sleep 1; fi; done"
        )

    @classmethod
    def _interactive_command(cls, command: str) -> str:
        """Keep launcher-only display controls out of the interactive frame."""
        names = " ".join(cls.INTERACTIVE_ENV_UNSET)
        return f"unset {names}; {command}"

    def _record_python(self, record: dict[str, Any]) -> str:
        source = record.get("source") or {}
        interpreter = source.get("interpreter")
        return interpreter if isinstance(interpreter, str) and interpreter else self.python

    @staticmethod
    def _sidebar_source_marker(record: dict[str, Any]) -> str:
        source = record.get("source") or {}
        marker = {
            "kind": source.get("kind"),
            "interpreter": source.get("interpreter"),
            "version": source.get("version"),
        }
        return json.dumps(marker, separators=(",", ":"), sort_keys=True)

    @classmethod
    def _agent_command(cls, record: dict[str, Any]) -> str:
        driver = record.get("driver") or {}
        argv = driver.get("launch_argv") or [os.environ.get("SHELL", "/bin/sh")]
        argv = cls._argv_with_handoff_prompt(argv, record)
        command = shlex.join(argv)
        handoff = record.get("handoff")
        if isinstance(handoff, dict) and handoff:
            lines = [
                "",
                "HIVE IDE handoff",
                f"- session: {handoff.get('session_name') or record.get('name')} ({record.get('id')})",
                f"- driver: {handoff.get('from_driver') or 'unknown'} -> {handoff.get('to_driver') or driver.get('id') or 'unknown'}",
                f"- cwd: {handoff.get('working_dir') or record.get('working_dir') or ''}",
            ]
            if handoff.get("plan"):
                lines.append(f"- plan: {handoff['plan']}")
            if handoff.get("active_task"):
                lines.append(f"- active task: {handoff['active_task']}")
            if handoff.get("target_driver_prompt"):
                driver_id = driver.get("id") or "driver"
                lines.extend(
                    [
                        "",
                        f"Handoff prompt sent to {driver_id}; agent should start below.",
                    ]
                )
            prefix = "printf %s " + shlex.quote("\n".join(lines) + "\n\n")
            command = f"{prefix}; {command}"
        return cls._interactive_command(
            f"{command}; status=$?; "
            'if [ "$status" -ne 0 ]; then '
            "printf '\\nhive-ide: driver command failed with exit %s\\n' \"$status\"; "
            "fi; "
            'exec "${SHELL:-/bin/sh}"'
        )

    @classmethod
    def _argv_with_handoff_prompt(
        cls, argv: list[str], record: dict[str, Any]
    ) -> list[str]:
        handoff = record.get("handoff")
        if not isinstance(handoff, dict):
            return argv
        prompt = handoff.get("target_driver_prompt")
        if not isinstance(prompt, str) or not prompt.strip():
            return argv
        driver_id = (record.get("driver") or {}).get("id")
        if driver_id not in {"claude", "codex"}:
            return argv
        return [*argv, prompt]

    def _plan_command(
        self, record: dict[str, Any], *, line: int | None = None
    ) -> str:
        try:
            path = self.plan_path(record)
        except UsageError:
            path = None
        if path is not None:
            editor = self._plan_pane_editor_argv(self._editor_argv())
            if line and line > 1 and Path(editor[0]).name in self.PLUS_LINE_EDITORS:
                editor.append(f"+{line}")
            return self._interactive_command(
                f"{shlex.join([*editor, str(path)])}; "
                'exec "${SHELL:-/bin/sh}"'
            )
        return self._interactive_command(
            'printf "\\n  No plan linked.\\n"; exec "${SHELL:-/bin/sh}"'
        )

    def safe_working_dir(self, record: dict[str, Any]) -> str:
        working_dir = Path(str(record.get("working_dir") or "")).expanduser()
        if working_dir.is_dir():
            return str(working_dir.resolve())
        return self.store.workspace_key

    @staticmethod
    def resolve_plan_path(reference: str | Path, record: dict[str, Any]) -> Path:
        path = Path(reference).expanduser()
        if path.is_absolute():
            candidates = [path]
        else:
            workspace = record.get("workspace_key")
            if not workspace:
                raise UsageError("Session workspace key is missing; cannot resolve plan path.")
            candidates = [Path(str(workspace)).expanduser() / path]
            working_dir = Path(str(record.get("working_dir") or "")).expanduser()
            if working_dir.is_dir():
                candidates.append(working_dir / path)

        for candidate in candidates:
            resolved = candidate.resolve()
            if resolved.is_file():
                return resolved
        checked = ", ".join(str(candidate.resolve()) for candidate in candidates)
        raise UsageError(f"Plan file does not exist: {checked}")

    @staticmethod
    def plan_path(record: dict[str, Any]) -> Path:
        reference = (record.get("plan") or {}).get("path")
        if not reference:
            raise UsageError("No plan is linked to this session.")
        return Frame.resolve_plan_path(reference, record)

    def _editor_argv(self) -> list[str]:
        configured = (self.settings.get("editor") or {}).get("argv")
        if (
            isinstance(configured, list)
            and configured
            and all(isinstance(value, str) for value in configured)
        ):
            return list(configured)
        return resolve_editor_argv({})

    @classmethod
    def _plan_pane_editor_argv(cls, editor: list[str]) -> list[str]:
        if not editor:
            return editor
        flags = cls.PLAN_PANE_READONLY_FLAGS.get(Path(editor[0]).name)
        if not flags:
            return list(editor)
        return [editor[0], *flags, *editor[1:]]

    def _send_micro_command(self, pane_id: str, command: str) -> None:
        self.tmux(["send-keys", "-t", pane_id, "C-e"])
        self.tmux(["send-keys", "-t", pane_id, command, "Enter"])

    def _pane_has_micro(self, pane_id: str) -> bool:
        current = self.tmux(
            ["display-message", "-p", "-t", pane_id, "#{pane_current_command}"]
        ).stdout.strip()
        if current == "micro":
            return True
        pid = self._pane_pid(pane_id)
        if pid is None:
            return False
        return any(
            self._process_command_name(candidate) == "micro"
            for candidate in self._process_tree(pid)
        )

    @staticmethod
    def _process_command_name(pid: int) -> str | None:
        try:
            name = Path(f"/proc/{pid}/comm").read_text(encoding="utf-8").strip()
        except OSError:
            name = ""
        if name:
            return name
        try:
            raw = Path(f"/proc/{pid}/cmdline").read_bytes().split(b"\0", 1)[0]
        except OSError:
            return None
        if not raw:
            return None
        return Path(raw.decode("utf-8", errors="replace")).name

    @staticmethod
    def plan_focus_line(path: Path) -> int:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            return 1
        todo = next(
            (
                index
                for index, text in enumerate(lines)
                if text.lstrip().startswith("- [ ]")
            ),
            None,
        )
        if todo is not None:
            return todo + 1
        done = next(
            (
                index
                for index, text in reversed(list(enumerate(lines)))
                if text.lstrip().lower().startswith("- [x]")
            ),
            None,
        )
        if done is not None:
            return done + 1
        tasks = next(
            (
                index
                for index, text in enumerate(lines)
                if text.strip() == "## Tasks"
            ),
            None,
        )
        return tasks + 1 if tasks is not None else 1

    @staticmethod
    def ensure_scratchpad(path: Path) -> int:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise HiveIdeError(f"Could not read plan {path}: {exc}") from exc
        lines = text.splitlines()
        scratchpad = next(
            (
                index
                for index, line in enumerate(lines)
                if line.strip().lower() == "## scratchpad"
            ),
            None,
        )
        if scratchpad is not None:
            return scratchpad + 1
        insert_at = next(
            (
                index
                for index, line in enumerate(lines)
                if line.strip() == "## Tasks"
            ),
            None,
        )
        if insert_at is None:
            insert_at = next(
                (
                    index
                    for index, line in enumerate(lines)
                    if line.strip().lower() in {"## status log", "## status"}
                ),
                None,
            )
        if insert_at is None:
            insert_at = len(lines)
        insert = ["## Scratchpad", ""]
        if insert_at > 0 and lines[insert_at - 1].strip():
            insert.insert(0, "")
        new_lines = [*lines[:insert_at], *insert, *lines[insert_at:]]
        try:
            path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        except OSError as exc:
            raise HiveIdeError(f"Could not update plan {path}: {exc}") from exc
        return insert_at + (2 if insert[0] == "" else 1)

    @staticmethod
    def tasks_line(path: Path) -> int | None:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise HiveIdeError(f"Could not read plan {path}: {exc}") from exc
        lines = text.splitlines()
        if not any(line.strip() == "## Tasks" for line in lines):
            return None
        return Frame.plan_focus_line(path)

    def scratchpad_editor_argv(self) -> list[str]:
        if shutil.which("micro"):
            return ["micro"]
        return self._editor_argv()

    def popup_size(self, *, width: str, height: str) -> tuple[str, str]:
        result = self.tmux(["display-message", "-p", "#{client_width}"])
        if result.returncode != 0:
            return width, height
        raw = result.stdout.strip()
        if raw.isdigit() and int(raw) < self.SIDEBAR_ZOOM_MAX:
            return "96%", "92%"
        return width, height

    def plan_popup(
        self, record: dict[str, Any], *, mode: str = "scratchpad"
    ) -> dict[str, Any]:
        path = self.plan_path(record)
        if mode == "scratchpad":
            line = self.ensure_scratchpad(path)
        elif mode == "tasks":
            line = self.tasks_line(path)
            if line is None:
                return {
                    "ok": False,
                    "reason": "no_tasks",
                    "session_id": record["id"],
                    "plan": str(path),
                }
        elif mode == "plan":
            line = 1
        else:
            raise UsageError(f"Unknown plan popup mode {mode!r}.")
        editor = self.scratchpad_editor_argv()
        if line > 1 and Path(editor[0]).name in self.PLUS_LINE_EDITORS:
            editor.append(f"+{line}")
        command = shlex.join([*editor, str(path)])
        width, height = self.popup_size(width="72%", height="70%")
        result = self.tmux(
            [
                "display-popup",
                "-E",
                "-w",
                width,
                "-h",
                height,
                command,
            ]
        )
        if result.returncode != 0:
            raise HiveIdeError(result.stderr.strip() or "Could not open Scratchpad.")
        return {
            "session_id": record["id"],
            "plan": str(path),
            "line": line,
            "opened": f"{mode}-popup",
        }

    def scratchpad(self, record: dict[str, Any]) -> dict[str, Any]:
        return self.plan_popup(record, mode="scratchpad")

    def current_plan(
        self, record: dict[str, Any], *, focus: bool = False
    ) -> dict[str, Any]:
        path = self.plan_path(record)
        line = self.plan_focus_line(path) if focus else None
        pane_id = self.role_panes(record["id"]).get("plan")
        if pane_id and os.environ.get("TMUX_PANE") != pane_id:
            if self._pane_has_micro(pane_id):
                self._send_micro_command(pane_id, "set readonly true")
                if focus:
                    self._send_micro_command(pane_id, f"goto {line}")
                    self.tmux(["select-pane", "-t", pane_id])
                return {
                    "session_id": record["id"],
                    "plan": str(path),
                    "line": line,
                    "opened": "plan-pane",
                }
            result = self.tmux(
                [
                    "respawn-pane",
                    "-k",
                    "-t",
                    pane_id,
                    "-c",
                    self.safe_working_dir(record),
                    "sh",
                    "-c",
                    self._plan_command(record, line=line),
                ]
            )
            if result.returncode != 0:
                raise HiveIdeError(result.stderr.strip() or "Could not reopen the plan pane.")
            self.tmux(["select-pane", "-T", self._plan_title(record), "-t", pane_id])
            if focus:
                self.tmux(["select-pane", "-t", pane_id])
            return {
                "session_id": record["id"],
                "plan": str(path),
                "line": line,
                "opened": "plan-pane",
            }
        editor = self._editor_argv()
        if line and line > 1 and Path(editor[0]).name in self.PLUS_LINE_EDITORS:
            editor.append(f"+{line}")
        result = subprocess.run([*editor, str(path)])
        if result.returncode != 0:
            raise HiveIdeError(f"The plan editor exited with status {result.returncode}.")
        return {
            "session_id": record["id"],
            "plan": str(path),
            "line": line,
            "opened": "terminal",
        }

    def current_chat(self, record: dict[str, Any]) -> dict[str, Any]:
        driver = record.get("driver") or {}
        argv = list(driver.get("launch_argv") or [])
        if not argv:
            raise UsageError("The session has no agent command to resume.")
        pane_id = self.role_panes(record["id"]).get("agent")
        if pane_id and os.environ.get("TMUX_PANE") != pane_id:
            current = self.tmux(
                ["display-message", "-p", "-t", pane_id, "#{pane_current_command}"]
            ).stdout.strip()
            if self.is_shell_agent_pane(record, current):
                self.respawn_agent(record, pane_id)
                self._clear_consumed_handoff(record)
                self.clear_sleep(record)
                self.tmux(["select-pane", "-t", pane_id])
                return {
                    "session_id": record["id"],
                    "driver": driver.get("id"),
                    "opened": "agent-pane",
                }
            self.clear_sleep(record)
            self.tmux(["select-pane", "-t", pane_id])
            return {
                "session_id": record["id"],
                "driver": driver.get("id"),
                "opened": "existing-agent-pane",
            }
        result = subprocess.run(argv, cwd=record["working_dir"])
        if result.returncode != 0:
            if driver.get("id") == "claude":
                fallback_argv = ["claude"]
                name = " ".join(str(record.get("name") or "").split())
                if name:
                    fallback_argv.extend(["--name", name])
                fallback = subprocess.run(fallback_argv, cwd=record["working_dir"])
                if fallback.returncode == 0:
                    self.clear_sleep(record)
                    return {
                        "session_id": record["id"],
                        "driver": driver.get("id"),
                        "opened": "claude",
                    }
            raise HiveIdeError(f"The agent exited with status {result.returncode}.")
        self.clear_sleep(record)
        return {
            "session_id": record["id"],
            "driver": driver.get("id"),
            "opened": "terminal",
        }

    def clear_sleep(self, record: dict[str, Any]) -> bool:
        if (record.get("sleep") or {}).get("state") != "sleeping":
            return False
        current = self.store.find_session(record["id"])
        if current is None:
            return False
        current.pop("sleep", None)
        current["last_active"] = utc_now()
        self.store.write("sessions", current["id"], current)
        self.store.delete("status", current["id"])
        return True

    @classmethod
    def is_shell_agent_pane(
        cls, record: dict[str, Any], current_command: str
    ) -> bool:
        driver = record.get("driver") or {}
        return driver.get("id") != "term" and Path(current_command).name in cls.SHELL_COMMANDS

    def agent_pane_command(self, record: dict[str, Any]) -> str | None:
        pane_id = self.role_panes(record["id"]).get("agent")
        if not pane_id:
            return None
        result = self.tmux(
            ["display-message", "-p", "-t", pane_id, "#{pane_current_command}"]
        )
        if result.returncode != 0:
            return None
        return result.stdout.strip()

    def agent_pane_pid(self, record: dict[str, Any]) -> int | None:
        pane_id = self.role_panes(record["id"]).get("agent")
        if not pane_id:
            return None
        result = self.tmux(["display-message", "-p", "-t", pane_id, "#{pane_pid}"])
        if result.returncode != 0:
            return None
        raw = result.stdout.strip()
        return int(raw) if raw.isdigit() else None

    def respawn_agent(self, record: dict[str, Any], pane_id: str) -> None:
        result = self.tmux(
            [
                "respawn-pane",
                "-k",
                "-t",
                pane_id,
                "-c",
                self.safe_working_dir(record),
                "sh",
                "-c",
                self._agent_command(record),
            ]
        )
        if result.returncode != 0:
            raise HiveIdeError(result.stderr.strip() or "Could not reopen the agent pane.")

    def sleep_agent(self, record: dict[str, Any]) -> dict[str, Any]:
        driver = record.get("driver") or {}
        if driver.get("id") == "term":
            raise UsageError("Terminal sessions do not have an agent to sleep.")
        pane_id = self.role_panes(record["id"]).get("agent")
        if not pane_id:
            return {
                "session_id": record["id"],
                "driver": driver.get("id"),
                "window_existed": record["id"] in self.windows(),
                "agent_pane_existed": False,
                "memory_released": False,
            }
        command = self._interactive_command(
            "printf '\\n  hive-ide: agent sleeping. Run `hive-ide chat` to wake.\\n\\n'; "
            'exec "${SHELL:-/bin/sh}"'
        )
        result = self.tmux(
            [
                "respawn-pane",
                "-k",
                "-t",
                pane_id,
                "-c",
                self.safe_working_dir(record),
                *self._environment(record),
                "sh",
                "-c",
                command,
            ]
        )
        if result.returncode != 0:
            raise HiveIdeError(result.stderr.strip() or "Could not sleep the agent pane.")
        return {
            "session_id": record["id"],
            "driver": driver.get("id"),
            "window_existed": True,
            "agent_pane_existed": True,
            "memory_released": True,
        }

    def refresh_sidebar_if_needed(self, record: dict[str, Any]) -> bool:
        pane_id = self.role_panes(record["id"]).get("sidebar")
        if not pane_id or not self._sidebar_needs_refresh(pane_id, record):
            return False
        result = self.tmux(
            [
                "respawn-pane",
                "-k",
                "-t",
                pane_id,
                "-c",
                self.safe_working_dir(record),
                "sh",
                "-c",
                self._sidebar_command(record),
            ]
        )
        if result.returncode != 0:
            raise HiveIdeError(result.stderr.strip() or "Could not refresh the sidebar pane.")
        self.tmux(["set-option", "-p", "-t", pane_id, "@hive_ide_pane", "sidebar"])
        self._tag_sidebar_source(pane_id, record)
        self.tmux(["select-pane", "-T", self._pane_titles(record)["sidebar"], "-t", pane_id])
        return True

    def _sidebar_needs_refresh(self, pane_id: str, record: dict[str, Any]) -> bool:
        marker = self.tmux(
            ["display-message", "-p", "-t", pane_id, "#{@hive_ide_sidebar_source}"]
        )
        if marker.returncode != 0:
            return self._sidebar_wrapper_is_stale(pane_id)
        value = marker.stdout.strip()
        if "\n" in value or "\t" in value:
            return self._sidebar_wrapper_is_stale(pane_id)
        if value != self._sidebar_source_marker(record):
            return True
        return self._sidebar_wrapper_is_stale(pane_id)

    def _tag_sidebar_source(self, pane_id: str, record: dict[str, Any]) -> None:
        self.tmux(
            [
                "set-option",
                "-p",
                "-t",
                pane_id,
                "@hive_ide_sidebar_source",
                self._sidebar_source_marker(record),
            ]
        )

    def _sidebar_wrapper_is_stale(self, pane_id: str) -> bool:
        result = self.tmux(["display-message", "-p", "-t", pane_id, "#{pane_pid}"])
        if result.returncode != 0:
            return False
        raw = result.stdout.strip()
        if not raw.isdigit():
            return False
        try:
            cmdline = Path(f"/proc/{raw}/cmdline").read_bytes().replace(b"\0", b" ")
        except OSError:
            return False
        return b"hive_ide.sidebar" in cmdline and b"window_active" not in cmdline

    def driver_rename(
        self, record: dict[str, Any], *, name: str | None = None
    ) -> dict[str, Any]:
        driver = record.get("driver") or {}
        driver_id = driver.get("id")
        display_name = " ".join(str(name or record.get("name") or "").split())
        if not display_name:
            raise UsageError("A session display name is required.")
        if driver_id not in {"claude", "codex"}:
            raise UsageError(
                "Interactive driver rename is currently supported only for Claude and Codex."
            )
        pane_id = self.role_panes(record["id"]).get("agent")
        if not pane_id:
            raise UsageError("The session has no live agent pane to rename.")
        result = self.tmux(
            ["send-keys", "-l", "-t", pane_id, f"/rename {display_name}"]
        )
        if result.returncode != 0:
            raise HiveIdeError(result.stderr.strip() or "Could not send driver rename.")
        result = self.tmux(["send-keys", "-t", pane_id, "Enter"])
        if result.returncode != 0:
            raise HiveIdeError(result.stderr.strip() or "Could not send driver rename.")
        return {
            "session_id": record["id"],
            "driver": driver_id,
            "name": display_name,
            "sent": "/rename",
        }

    def _clear_consumed_handoff(self, record: dict[str, Any]) -> None:
        if not isinstance(record.get("handoff"), dict):
            return
        fresh = self.store.read("sessions", record["id"]) or record
        if isinstance(fresh.get("handoff"), dict):
            fresh.pop("handoff", None)
            self.store.write("sessions", record["id"], fresh)
        record.pop("handoff", None)

    def _tag(
        self,
        target: str,
        record: dict[str, Any],
        role_panes: dict[str, str] | None = None,
    ) -> None:
        self.tmux(["set-option", "-w", "-t", target, "automatic-rename", "off"])
        self.tmux(["set-option", "-w", "-t", target, "allow-rename", "off"])
        self.tmux(["rename-window", "-t", target, record["name"]])
        for key, value in (
            ("@hive_ide_session_id", record["id"]),
            ("@hive_ide_workspace_hash", self.store.workspace_hash),
            ("@hive_ide_workspace_key", self.store.workspace_key),
        ):
            self.tmux(["set-option", "-w", "-t", target, key, value])
        if role_panes is None:
            role_panes = {
                role: f"{target}.{index}"
                for index, role in enumerate(self.PANE_ROLES)
            }
        for role, pane in role_panes.items():
            self.tmux(["set-option", "-p", "-t", pane, "@hive_ide_pane", role])
            if role == "sidebar":
                self._tag_sidebar_source(pane, record)
        self._retitle_panes(target, record)

    def _retitle_panes(self, target: str, record: dict[str, Any]) -> None:
        titles = self._pane_titles(record)
        roles = self._order_role_panes(target)
        for role, title in titles.items():
            pane = roles.get(role)
            if pane:
                self.tmux(["select-pane", "-T", title, "-t", pane])
                self.tmux(["set-option", "-p", "-t", pane, "@hive_ide_title", title])

    def retitle_panes(self, record: dict[str, Any]) -> bool:
        target = self.windows().get(record["id"])
        if not target:
            return False
        titles = self._pane_titles(record)
        roles = self._order_role_panes(target)
        changed = False
        for role, title in titles.items():
            pane = roles.get(role)
            if not pane:
                continue
            current = self.tmux(
                ["display-message", "-p", "-t", pane, "#{@hive_ide_title}"]
            ).stdout.strip()
            if current != title:
                changed = True
                break
        if changed:
            self._retitle_panes(target, record)
        return changed

    def _pane_titles(self, record: dict[str, Any]) -> dict[str, str]:
        workspace = Path(self.store.workspace_key).name or self.store.workspace_hash[:8]
        return {
            "sidebar": workspace,
            "agent": str(record.get("name") or "chat"),
            "plan": self._plan_title(record),
        }

    def _plan_title(self, record: dict[str, Any]) -> str:
        try:
            path = self.plan_path(record)
        except UsageError:
            return "No plan"
        title = self._plan_internal_title(path)
        return title or path.stem.replace("-", " ").replace("_", " ").title()

    @staticmethod
    def _plan_internal_title(path: Path) -> str | None:
        try:
            for line in path.read_text(encoding="utf-8").splitlines():
                text = line.strip()
                if text.startswith("# "):
                    value = text[2:].strip()
                    return value or None
        except OSError:
            return None
        return None

    def _apply_columns(self, target: str) -> None:
        roles = self._order_role_panes(target)
        sidebar_pane = roles.get("sidebar", f"{target}.0")
        plan_pane = roles.get("plan", f"{target}.2")
        width = self.tmux(
            ["display-message", "-p", "-t", target, "#{window_width}"]
        ).stdout.strip()
        columns = IdeLayout.columns(int(width)) if width.isdigit() else None
        if columns is None:
            self.tmux(["select-pane", "-t", sidebar_pane])
            zoomed = self.tmux(
                ["display-message", "-p", "-t", target, "#{window_zoomed_flag}"]
            ).stdout.strip()
            if zoomed != "1":
                self.tmux(["resize-pane", "-Z", "-t", sidebar_pane])
            return
        sidebar, _, plan = columns
        self.tmux(["resize-pane", "-t", sidebar_pane, "-x", str(sidebar)])
        self.tmux(["resize-pane", "-t", plan_pane, "-x", str(plan)])

    def build(self, record: dict[str, Any]) -> str:
        working_dir = record["working_dir"]
        if not Path(working_dir).is_dir():
            raise UsageError(f"Session working directory does not exist: {working_dir}")
        interpreter = (record.get("source") or {}).get("interpreter") or self.python
        self._refresh_source_if_needed(record, interpreter)
        env = self._environment(record)
        sidebar = ["sh", "-c", self._sidebar_command(record)]
        if self.exists():
            created = self.tmux(
                [
                    "new-window",
                    "-d",
                    "-t",
                    self.target,
                    "-n",
                    record["name"],
                    "-P",
                    "-F",
                    "#{window_id}",
                    "-c",
                    working_dir,
                    *env,
                    *sidebar,
                ]
            )
        else:
            created = self.tmux(
                [
                    "new-session",
                    "-d",
                    "-s",
                    self.target,
                    "-n",
                    record["name"],
                    "-P",
                    "-F",
                    "#{window_id}",
                    "-c",
                    working_dir,
                    *env,
                    *sidebar,
                ],
                clean_start=True,
            )
        if created.returncode != 0:
            raise HiveIdeError(created.stderr.strip() or f"Could not create window {record['name']}.")
        target = created.stdout.strip()
        if not target:
            raise HiveIdeError(f"tmux did not return an id for window {record['name']}.")
        for command in (self._agent_command(record), self._plan_command(record)):
            result = self.tmux(
                [
                    "split-window",
                    "-h",
                    "-t",
                    target,
                    "-c",
                    working_dir,
                    *env,
                    "sh",
                    "-c",
                    command,
                ]
            )
            if result.returncode != 0:
                raise HiveIdeError(result.stderr.strip() or f"Could not split window {record['name']}.")
        self._tag(target, record)
        self._apply_columns(target)
        self.tmux(["select-pane", "-t", f"{target}.0"])
        self._clear_consumed_handoff(record)
        return target

    def ensure(self, record: dict[str, Any]) -> bool:
        if record["id"] in self.windows():
            return False
        self.build(record)
        return True

    def restore_missing_panes(
        self, record: dict[str, Any], missing_roles: tuple[str, ...]
    ) -> tuple[str, ...]:
        target = self.windows().get(record["id"])
        if not target:
            return ()
        restored: list[str] = []
        env = self._environment(record)
        working_dir = self.safe_working_dir(record)
        commands = {
            "sidebar": self._sidebar_command(record),
            "plan": self._plan_command(record),
        }
        for role in missing_roles:
            command = commands.get(role)
            if command is None:
                continue
            created = self.tmux(
                [
                    "split-window",
                    "-h",
                    "-t",
                    target,
                    "-P",
                    "-F",
                    "#{pane_id}",
                    "-c",
                    working_dir,
                    *env,
                    "sh",
                    "-c",
                    command,
                ]
            )
            if created.returncode != 0:
                raise HiveIdeError(
                    created.stderr.strip() or f"Could not restore {role} pane."
                )
            pane_id = created.stdout.strip()
            if pane_id:
                self.tmux(["set-option", "-p", "-t", pane_id, "@hive_ide_pane", role])
                if role == "sidebar":
                    self._tag_sidebar_source(pane_id, record)
            restored.append(role)
        if restored:
            self._retitle_panes(target, record)
            self._apply_columns(target)
        return tuple(restored)

    def select_session(self, session_id: str, *, pane: int = 1) -> bool:
        target = self.windows().get(session_id)
        if not target:
            return False
        self.tmux(["select-window", "-t", target])
        roles = self._order_role_panes(target)
        role = self.PANE_ROLES[pane] if 0 <= pane < len(self.PANE_ROLES) else None
        pane_target = roles.get(role or "", f"{target}.{pane}")
        self.tmux(["select-pane", "-t", pane_target])
        return True

    def rebuild(self, record: dict[str, Any]) -> None:
        existing = self.windows().get(record["id"])
        previous_index = None
        selected = False
        active_before = self.tmux(
            ["display-message", "-p", "-t", self.target, "#{window_id}.#{pane_index}"]
        ).stdout.strip()
        if existing:
            previous_index = self.tmux(
                ["display-message", "-p", "-t", existing, "#{window_index}"]
            ).stdout.strip() or None
            selected = (
                self.tmux(
                    ["display-message", "-p", "-t", existing, "#{window_active}"]
                ).stdout.strip()
                == "1"
            )
        replacement = self.build(record)
        if existing:
            self.tmux(["kill-window", "-t", existing])
        if previous_index and replacement:
            current_index = self.tmux(
                ["display-message", "-p", "-t", replacement, "#{window_index}"]
            ).stdout.strip()
            if current_index != previous_index:
                moved = self.tmux(
                    [
                        "move-window",
                        "-s",
                        replacement,
                        "-t",
                        f"{self.target}:{previous_index}",
                    ]
                )
                if moved.returncode != 0:
                    raise HiveIdeError(
                        moved.stderr.strip()
                        or f"Could not preserve window index {previous_index}."
                    )
                replacement = self.windows().get(record["id"], replacement)
        if selected and replacement:
            self.tmux(["select-window", "-t", replacement])
            self.tmux(["select-pane", "-t", f"{replacement}.1"])
        elif replacement:
            self.tmux(["select-window", "-t", replacement])
            self.tmux(["select-pane", "-t", f"{replacement}.1"])
            self.tmux(["send-keys", "-t", f"{replacement}.1", "C-l"])
            if active_before:
                self.tmux(["select-pane", "-t", active_before])

    def close(self, session_id: str) -> bool:
        window_id = self.windows().get(session_id)
        if not window_id:
            return False
        return self.tmux(["kill-window", "-t", window_id]).returncode == 0

    def rename(self, session_id: str, display_name: str) -> bool:
        window_id = self.windows().get(session_id)
        if not window_id:
            return False
        return (
            self.tmux(["rename-window", "-t", window_id, display_name]).returncode
            == 0
        )

    def _key_bindings(self) -> dict[str, str | None]:
        settings = self.settings.get("keys") or {}
        bindings = settings.get("bindings")
        if isinstance(bindings, dict):
            return {**DEFAULT_KEYS["bindings"], **bindings}
        return dict(DEFAULT_KEYS["bindings"])

    def _terminal_title(self) -> str:
        workspace = Path(self.store.workspace_key).name or self.store.workspace_hash[:8]
        host = self._ssh_host_title_suffix()
        if host:
            return f"{workspace} IDE {host}"
        return f"{workspace} IDE"

    @classmethod
    def _ssh_host_title_suffix(cls) -> str | None:
        if not cls._is_ssh_session():
            return None
        override = cls._clean_title_label(os.environ.get("HIVE_IDE_HOST_NAME"))
        if override:
            return override
        return cls._clean_title_label(os.environ.get("HOSTNAME") or os.uname().nodename)

    @staticmethod
    def _is_ssh_session() -> bool:
        return bool(os.environ.get("SSH_CONNECTION") or os.environ.get("SSH_CLIENT"))

    @staticmethod
    def _clean_title_label(value: str | None) -> str | None:
        if not value:
            return None
        label = value.strip().strip("[]").split(".", 1)[0]
        label = re.sub(r"[^A-Za-z0-9_-]+", "-", label).strip("-_")
        return label[:24] or None

    def _normalize_terminal_title(self) -> None:
        title = self._terminal_title()
        self.tmux(["set-option", "-g", "set-titles", "on"])
        self.tmux(["set-option", "-g", "set-titles-string", title])
        self.tmux(["set-option", "-t", self.target, "set-titles", "on"])
        self.tmux(["set-option", "-t", self.target, "set-titles-string", title])

    def _normalize_frame_environment(self) -> None:
        for name in self.INTERACTIVE_ENV_UNSET:
            self.tmux(["set-environment", "-g", "-u", name])

    def _normalize_status_rows(self) -> None:
        """Keep the dedicated IDE frame to its single window-status row."""
        options = self.tmux(["show-options", "-g", "status-format"])
        for line in options.stdout.splitlines():
            name = line.partition(" ")[0]
            if re.fullmatch(r"status-format\[(?!0\])\d+\]", name):
                self.tmux(["set-option", "-g", "-u", name])

    def _normalize_pane_titlebars(self) -> None:
        self.tmux(["set-option", "-g", "pane-border-status", "top"])
        self.tmux(["set-option", "-g", "pane-active-border-style", "fg=colour51"])
        self.tmux(["set-option", "-g", "pane-border-style", "fg=colour238"])
        self.tmux(
            [
                "set-option",
                "-g",
                "pane-border-format",
                "#{?pane_active,#[fg=colour16;bg=colour51;bold],#[fg=colour244]} "
                "#{@hive_ide_title} #[default]",
            ]
        )

    def _normalize_resize_behavior(self) -> None:
        """Follow the latest attached client so mobile SSH cannot pin desktop geometry."""
        self.tmux(["set-option", "-g", "window-size", "latest"])
        self.tmux(["set-window-option", "-g", "aggressive-resize", "off"])
        for window_id in self.windows().values():
            self.tmux(["set-window-option", "-t", window_id, "aggressive-resize", "off"])

    def bind_keys(self) -> None:
        self._normalize_frame_environment()
        self._normalize_status_rows()
        self._normalize_terminal_title()
        self._normalize_pane_titlebars()
        self._normalize_resize_behavior()
        keys = self._key_bindings()
        prefix = (self.settings.get("keys") or {}).get("prefix")
        base_prefix = self.tmux(
            ["show-option", "-gvq", "@hive_ide_base_prefix"]
        ).stdout.strip()
        if not base_prefix:
            base_prefix = self.tmux(["show-option", "-gv", "prefix"]).stdout.strip()
            if base_prefix:
                self.tmux(
                    ["set-option", "-g", "@hive_ide_base_prefix", base_prefix]
                )
        if prefix:
            self.tmux(["set-option", "-g", "prefix", prefix])
        elif base_prefix:
            self.tmux(["set-option", "-g", "prefix", base_prefix])
        previous_keys = self.tmux(
            ["show-option", "-gvq", "@hive_ide_bound_keys"]
        ).stdout.split()
        for previous in previous_keys:
            self.tmux(["unbind-key", previous])
        self.tmux(["set-option", "-g", "mouse", "on"])
        self.tmux(["set-option", "-g", "focus-events", "on"])
        self.tmux(["set-option", "-s", "extended-keys", "on"])
        self.tmux(["set-option", "-as", "terminal-features", "xterm*:extkeys"])
        new_modal = self._module(
            "newmodal",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
            ],
        )
        mobile_popup = f"#{{<:#{{client_width}},{self.SIDEBAR_ZOOM_MAX}}}"
        new_popup_width = "#{?" + mobile_popup + ",96%,52%}"
        new_popup_height = "#{?" + mobile_popup + ",92%,42%}"
        if key := keys.get("new"):
            self.tmux(
                [
                    "bind-key",
                    key,
                    "display-popup",
                    "-E",
                    "-w",
                    new_popup_width,
                    "-h",
                    new_popup_height,
                    new_modal,
                ]
            )
        for action, kind in (
            ("agent", "agent"),
            ("options", "options"),
            ("card", "card"),
            ("help", "keys"),
            ("error", "error"),
        ):
            key = keys.get(action)
            if not key:
                continue
            popup = self._module(
                "popup",
                [
                    "--kind",
                    kind,
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                ],
            )
            self.tmux(["bind-key", key, "run-shell", "-b", popup])
        if key := keys.get("jump_plan"):
            focus = self._module(
                "cli",
                [
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "plan",
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                    "--focus",
                ],
            )
            self.tmux(["bind-key", key, "run-shell", "-b", f"{focus} >/dev/null 2>&1"])
        if key := keys.get("scratchpad"):
            scratchpad = self._module(
                "cli",
                [
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--quiet",
                    "scratchpad",
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                ],
            )
            self.tmux(
                ["bind-key", key, "run-shell", "-b", f"{scratchpad} >/dev/null 2>&1"]
            )
        for action, direction in (("next", "next"), ("previous", "prev")):
            key = keys.get(action)
            if not key:
                continue
            command = self._module(
                "nav",
                [
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                    "--direction",
                    direction,
                ],
            )
            self.tmux(["bind-key", key, "run-shell", "-b", command])
        relayout = self._module(
            "relayout",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
                "--mode",
                "snap",
            ],
        )
        relayout_window = self._module(
            "relayout",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
                "--mode",
                "snap",
                "--client-width",
                "#{window_width}",
                "--client-height",
                "#{window_height}",
                "--window-id",
                "#{window_id}",
            ],
        )
        if key := keys.get("reset"):
            repair = self._module(
                "cli",
                [
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--quiet",
                    "repair",
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                ],
            )
            self.tmux(
                [
                    "bind-key",
                    key,
                    "run-shell",
                    "-b",
                    f"{repair} >/dev/null 2>&1; {relayout} >/dev/null 2>&1",
                ]
            )
        seen = self._module(
            "seen",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--session-id",
                "#{@hive_ide_session_id}",
            ],
        )
        self.tmux(
            [
                "set-hook",
                "-t",
                self.target,
                "session-window-changed",
                f"run-shell -b {shlex.quote(seen)}",
            ]
        )
        adopt = self._module(
            "relayout",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
                "--mode",
                "adopt",
            ],
        )
        self.tmux(
            [
                "set-hook",
                "-a",
                "-t",
                self.target,
                "session-window-changed",
                f"run-shell -b {shlex.quote(adopt)}",
            ]
        )
        self.tmux(
            [
                "set-hook",
                "-t",
                self.target,
                "client-resized",
                f"run-shell -b {shlex.quote(relayout_window)}",
            ]
        )
        self.tmux(
            [
                "set-hook",
                "-t",
                self.target,
                "client-attached",
                f"run-shell -b {shlex.quote(relayout_window)}",
            ]
        )
        for redundant_hook in ("client-active", "client-focus-in"):
            self.tmux(["set-hook", "-t", self.target, "-u", redundant_hook])
        self.tmux(["set-hook", "-t", self.target, "-u", "after-select-pane"])
        sidebar_key = keys.get("sidebar")
        if sidebar_key:
            self.tmux(
                [
                    "bind-key",
                    sidebar_key,
                    "if-shell",
                    "-F",
                    f"#{{<:#{{client_width}},{self.SIDEBAR_ZOOM_MAX}}}",
                    "if-shell -F '#{window_zoomed_flag}' 'resize-pane -Z ; select-pane -t .0 ; resize-pane -Z' 'select-pane -t .0 ; resize-pane -Z'",
                    "select-pane -t .0",
                ]
            )
        for action, index in (("chat", "1"), ("plan", "2")):
            key = keys.get(action)
            if not key:
                continue
            self.tmux(
                [
                    "bind-key",
                    key,
                    "if-shell",
                    "-F",
                    f"#{{<:#{{client_width}},{self.SIDEBAR_ZOOM_MAX}}}",
                    f"if-shell -F '#{{window_zoomed_flag}}' 'resize-pane -Z ; select-pane -t .{index} ; resize-pane -Z' 'select-pane -t .{index} ; resize-pane -Z'",
                    "if-shell -F '#{window_zoomed_flag}' "
                    f"'resize-pane -Z ; select-pane -t .{index}' "
                    f"'select-pane -t .{index}'",
                ]
            )
        bound = sorted({key for key in keys.values() if key})
        self.tmux(
            ["set-option", "-g", "@hive_ide_bound_keys", " ".join(bound)]
        )

    def verify_user_config(self) -> list[str]:
        findings: list[str] = []
        for path in (Path.home() / ".tmux.conf", Path.home() / ".config/tmux/tmux.conf"):
            if not path.exists():
                continue
            try:
                lines = path.read_text(encoding="utf-8").splitlines()
            except OSError:
                continue
            for option in self.DEPENDED_OPTIONS:
                hits = [
                    (index + 1, line.strip())
                    for index, line in enumerate(lines)
                    if re.match(rf"\s*set(-option)?\s+(-\w+\s+)*{option}\b", line)
                ]
                if len(hits) > 1:
                    positions = ", ".join(f"line {line}" for line, _ in hits)
                    findings.append(
                        f"WARN {path.name}: `{option}` set {len(hits)}x ({positions}); "
                        f"last wins: {hits[-1][1]!r}"
                    )
        return findings

    def _record_open_error(
        self, record: dict[str, Any], error: HiveIdeError
    ) -> dict[str, str]:
        detail = str(error)
        self.store.write(
            "errors",
            record["id"],
            {
                "schema_version": SCHEMA_VERSION,
                "workspace_key": self.store.workspace_key,
                "session_id": record["id"],
                "component": "frame:open",
                "summary": f"Could not open session {record['name']}",
                "detail": detail[:8192],
                "retryable": True,
                "recovery": (
                    "Fix the reported session directory or package source, then run "
                    "hive-ide open again."
                ),
                "observed_at": utc_now(),
            },
        )
        return {"session_id": record["id"], "name": record["name"], "error": detail}

    def _clear_open_error(self, record: dict[str, Any]) -> None:
        current = self.store.read("errors", record["id"])
        if current and current.get("component") == "frame:open":
            self.store.delete("errors", record["id"])

    def open(self, *, no_attach: bool = False) -> dict[str, Any]:
        self.require_tmux()
        sessions = self.store.list("sessions")
        if not sessions:
            raise UsageError("This workspace has no sessions. Run hive-ide create first.")
        current_window = None
        if self.exists():
            current_window = self.tmux(
                ["display-message", "-p", "-t", self.target, "#{window_id}"]
            ).stdout.strip() or None
        built: list[str] = []
        failed: list[dict[str, str]] = []
        for record in sessions:
            try:
                if self.ensure(record):
                    built.append(record["id"])
            except HiveIdeError as exc:
                failed.append(self._record_open_error(record, exc))
                continue
            self._clear_open_error(record)
        windows = self.windows()
        if not windows:
            raise UsageError(
                f"No session windows could be opened; {len(failed)} session(s) failed. "
                "Run hive-ide verify and inspect the recorded session errors."
            )
        self.bind_keys()
        selected_window = (
            current_window
            if current_window in windows.values()
            else next(
                (
                    windows.get(record["id"])
                    for record in sessions
                    if windows.get(record["id"])
                ),
                None,
            )
        )
        if selected_window and selected_window != current_window:
            self.tmux(["select-window", "-t", selected_window])
        if not no_attach:
            os.execvp("tmux", ["tmux", "-L", self.socket, "attach", "-t", self.target])
        return {
            "tmux_socket": self.socket,
            "tmux_session": self.target,
            "built": built,
            "failed": failed,
            "windows": len(windows),
        }
