"""tmux frame construction and repair."""

from __future__ import annotations

import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from . import PROTOCOL_VERSION, SCHEMA_VERSION, __version__
from .config import DEFAULT_KEYS, _editor_argv as resolve_editor_argv
from .errors import HiveIdeError, UsageError
from .layout import IdeLayout
from .source import inspect_interpreter
from .store import StateStore, utc_now


class Frame:
    PANE_ROLES = ("sidebar", "agent", "plan")
    SIDEBAR_W = IdeLayout.SIDEBAR_W
    PLAN_W = IdeLayout.PLAN_W
    AGENT_PREF = IdeLayout.AGENT_PREF
    SIDEBAR_ZOOM_MAX = IdeLayout.mobile_threshold()
    DEPENDED_OPTIONS = ("mouse", "prefix", "focus-events")
    USER_CONFS = (".tmux.conf", ".config/tmux/tmux.conf")
    PLUS_LINE_EDITORS = {
        "micro",
        "vim",
        "nvim",
        "vi",
        "view",
        "gvim",
        "nano",
        "emacs",
        "emacsclient",
    }

    def __init__(self, store: StateStore, *, socket: str | None = None):
        self.store = store
        self.settings = store.read_path(store.config_snapshot_path()) or {}
        saved_tmux = self.settings.get("tmux") or {}
        self.socket = (
            socket
            or saved_tmux.get("socket")
            or f"hive-ide-{store.workspace_hash[:8]}"
        )
        self.target = f"hive-ide-{store.workspace_hash[:8]}"
        self.python = sys.executable

    def _ide_conf(self) -> Path | None:
        """Copy the user's tmux config while disabling continuum for this server."""
        source = next(
            (
                path
                for relative in self.USER_CONFS
                if (path := Path.home() / relative).is_file()
            ),
            None,
        )
        if source is None:
            return None
        output = self.store.workspace_dir / "ide.conf"
        try:
            original = source.read_text(encoding="utf-8").splitlines()
        except OSError as exc:
            raise UsageError(f"Could not read tmux config {source}: {exc}") from exc
        lines = [
            f"# Generated by hive-ide from {source}; do not edit.",
            "# tmux-continuum restore and autosave are disabled for this server only.",
            "",
        ]
        save_disabled = False
        for line in original:
            if re.match(r"^\s*set\b.*@continuum-restore", line):
                lines.extend(
                    [f"# [hive-ide] was: {line.strip()}", "set -g @continuum-restore 'off'"]
                )
            elif re.match(r"^\s*set\b.*@continuum-save-interval", line):
                lines.append(f"# [hive-ide] was: {line.strip()}")
            else:
                if re.match(r"^\s*run\b.*tpm", line) and not save_disabled:
                    lines.append(
                        "set -g @continuum-save-interval '0' # hive-ide never autosaves"
                    )
                    save_disabled = True
                lines.append(line)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return output

    def tmux(
        self, args: list[str], *, clean_start: bool = False
    ) -> subprocess.CompletedProcess[str]:
        generated = self._ide_conf() if clean_start else None
        config = ["-f", str(generated)] if generated else []
        return subprocess.run(
            ["tmux", "-L", self.socket, *config, *args],
            capture_output=True,
            text=True,
        )

    def require_tmux(self) -> None:
        if shutil.which("tmux") is None:
            raise UsageError("tmux is required but was not found on PATH.")
        handshake = subprocess.run(
            [
                self.python,
                "-I",
                "-m",
                "hive_ide.cli",
                "version",
            ],
            capture_output=True,
            text=True,
        )
        if handshake.returncode != 0:
            raise UsageError(
                "The selected Python interpreter cannot import hive_ide in isolated mode. "
                "Install the package into that environment; user-site installs are hidden by -I."
            )

    def exists(self) -> bool:
        return self.tmux(["has-session", "-t", self.target]).returncode == 0

    def windows(self) -> dict[str, str]:
        if not self.exists():
            return {}
        result = self.tmux(
            [
                "list-windows",
                "-t",
                self.target,
                "-F",
                "#{@hive_ide_session_id}\t#{window_id}",
            ]
        )
        if result.returncode != 0:
            return {}
        rows: dict[str, str] = {}
        for line in result.stdout.splitlines():
            session_id, _, window_id = line.partition("\t")
            if session_id:
                rows[session_id] = window_id
        return rows

    def role_panes(self, session_id: str) -> dict[str, str]:
        window_id = self.windows().get(session_id)
        if not window_id:
            return {}
        result = self.tmux(
            [
                "list-panes",
                "-t",
                window_id,
                "-F",
                "#{@hive_ide_pane}\t#{pane_id}",
            ]
        )
        if result.returncode != 0:
            return {}
        return {
            role: pane_id
            for line in result.stdout.splitlines()
            for role, _, pane_id in [line.partition("\t")]
            if role and pane_id
        }

    def _module(
        self, module: str, args: list[str], *, interpreter: str | None = None
    ) -> str:
        return shlex.join(
            [interpreter or self.python, "-I", "-m", f"hive_ide.{module}", *args]
        )

    def _environment(self, record: dict[str, Any]) -> list[str]:
        source = record.get("source") or {}
        return [
            "-e",
            f"HIVE_IDE_PROTOCOL_VERSION={PROTOCOL_VERSION}",
            "-e",
            f"HIVE_IDE_VERSION={__version__}",
            "-e",
            f"HIVE_IDE_STATE_HOME={self.store.home}",
            "-e",
            f"HIVE_IDE_WORKSPACE_KEY={self.store.workspace_key}",
            "-e",
            f"HIVE_IDE_TMUX_SOCKET={self.socket}",
            "-e",
            f"HIVE_IDE_SESSION_ID={record['id']}",
            "-e",
            f"HIVE_IDE_SESSION={record['name']}",
            "-e",
            f"HIVE_IDE_SOURCE={source.get('kind') or 'stable'}",
        ]

    def _sidebar_command(self, record: dict[str, Any]) -> str:
        interpreter = (record.get("source") or {}).get("interpreter") or self.python
        command = self._module(
            "sidebar",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--session-id",
                record["id"],
                "--tmux-socket",
                self.socket,
            ],
            interpreter=interpreter,
        )
        return f"while :; do {command}; sleep 1; done"

    @staticmethod
    def _agent_command(record: dict[str, Any]) -> str:
        argv = (record.get("driver") or {}).get("launch_argv") or [os.environ.get("SHELL", "/bin/sh")]
        return f"{shlex.join(argv)}; exec \"${{SHELL:-/bin/sh}}\""

    def _plan_command(
        self, record: dict[str, Any], *, line: int | None = None
    ) -> str:
        plan = (record.get("plan") or {}).get("path")
        if plan:
            path = Path(plan)
            if not path.is_absolute():
                path = Path(record["working_dir"]) / path
            if path.is_file():
                editor = self._editor_argv()
                if (
                    line
                    and line > 1
                    and Path(editor[0]).name in self.PLUS_LINE_EDITORS
                ):
                    editor.append(f"+{line}")
                return (
                    f"{shlex.join([*editor, str(path)])}; "
                    'exec "${SHELL:-/bin/sh}"'
                )
        return 'printf "\\n  No plan linked.\\n"; exec "${SHELL:-/bin/sh}"'

    @staticmethod
    def plan_path(record: dict[str, Any]) -> Path:
        reference = (record.get("plan") or {}).get("path")
        if not reference:
            raise UsageError("No plan is linked to this session.")
        path = Path(reference).expanduser()
        if not path.is_absolute():
            path = Path(record["working_dir"]) / path
        path = path.resolve()
        if not path.is_file():
            raise UsageError(f"Plan file does not exist: {path}")
        return path

    def _editor_argv(self) -> list[str]:
        configured = (self.settings.get("editor") or {}).get("argv")
        if (
            isinstance(configured, list)
            and configured
            and all(isinstance(value, str) for value in configured)
        ):
            return list(configured)
        return resolve_editor_argv({})

    @staticmethod
    def plan_focus_line(path: Path) -> int:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            return 1
        todo = next(
            (
                index
                for index, text in enumerate(lines)
                if text.lstrip().startswith("- [ ]")
            ),
            None,
        )
        if todo is not None:
            for index in range(todo, -1, -1):
                if lines[index].startswith(("## ", "### ")):
                    return index + 1
            return todo + 1
        tasks = next(
            (
                index
                for index, text in enumerate(lines)
                if text.strip() == "## Tasks"
            ),
            None,
        )
        return tasks + 1 if tasks is not None else 1

    def current_plan(
        self, record: dict[str, Any], *, focus: bool = False
    ) -> dict[str, Any]:
        path = self.plan_path(record)
        line = self.plan_focus_line(path) if focus else None
        pane_id = self.role_panes(record["id"]).get("plan")
        if pane_id and os.environ.get("TMUX_PANE") != pane_id:
            current = self.tmux(
                ["display-message", "-p", "-t", pane_id, "#{pane_current_command}"]
            ).stdout.strip()
            if focus and current == "micro":
                self.tmux(["send-keys", "-t", pane_id, "C-e"])
                self.tmux(["send-keys", "-t", pane_id, f"goto {line}", "Enter"])
                self.tmux(["select-pane", "-t", pane_id])
                return {
                    "session_id": record["id"],
                    "plan": str(path),
                    "line": line,
                    "opened": "plan-pane",
                }
            result = self.tmux(
                [
                    "respawn-pane",
                    "-k",
                    "-t",
                    pane_id,
                    "-c",
                    record["working_dir"],
                    "sh",
                    "-c",
                    self._plan_command(record, line=line),
                ]
            )
            if result.returncode != 0:
                raise HiveIdeError(result.stderr.strip() or "Could not reopen the plan pane.")
            self.tmux(["select-pane", "-t", pane_id])
            return {
                "session_id": record["id"],
                "plan": str(path),
                "line": line,
                "opened": "plan-pane",
            }
        editor = self._editor_argv()
        if line and line > 1 and Path(editor[0]).name in self.PLUS_LINE_EDITORS:
            editor.append(f"+{line}")
        result = subprocess.run([*editor, str(path)])
        if result.returncode != 0:
            raise HiveIdeError(f"The plan editor exited with status {result.returncode}.")
        return {
            "session_id": record["id"],
            "plan": str(path),
            "line": line,
            "opened": "terminal",
        }

    def current_chat(self, record: dict[str, Any]) -> dict[str, Any]:
        driver = record.get("driver") or {}
        argv = list(driver.get("launch_argv") or [])
        if not argv:
            raise UsageError("The session has no agent command to resume.")
        reference = (driver.get("resume") or {}).get("reference")
        if driver.get("id") != "term" and not reference:
            raise UsageError(
                "No conversation reference has been observed for this session yet."
            )
        pane_id = self.role_panes(record["id"]).get("agent")
        if pane_id and os.environ.get("TMUX_PANE") != pane_id:
            result = self.tmux(
                [
                    "respawn-pane",
                    "-k",
                    "-t",
                    pane_id,
                    "-c",
                    record["working_dir"],
                    "sh",
                    "-c",
                    self._agent_command(record),
                ]
            )
            if result.returncode != 0:
                raise HiveIdeError(result.stderr.strip() or "Could not reopen the agent pane.")
            self.tmux(["select-pane", "-t", pane_id])
            return {
                "session_id": record["id"],
                "driver": driver.get("id"),
                "opened": "agent-pane",
            }
        result = subprocess.run(argv, cwd=record["working_dir"])
        if result.returncode != 0:
            raise HiveIdeError(f"The agent exited with status {result.returncode}.")
        return {
            "session_id": record["id"],
            "driver": driver.get("id"),
            "opened": "terminal",
        }

    def _tag(self, target: str, record: dict[str, Any]) -> None:
        self.tmux(["set-option", "-w", "-t", target, "automatic-rename", "off"])
        self.tmux(["set-option", "-w", "-t", target, "allow-rename", "off"])
        self.tmux(["rename-window", "-t", target, record["name"]])
        for key, value in (
            ("@hive_ide_session_id", record["id"]),
            ("@hive_ide_workspace_hash", self.store.workspace_hash),
            ("@hive_ide_workspace_key", self.store.workspace_key),
        ):
            self.tmux(["set-option", "-w", "-t", target, key, value])
        for index, role in enumerate(self.PANE_ROLES):
            self.tmux(["set-option", "-p", "-t", f"{target}.{index}", "@hive_ide_pane", role])

    def _apply_columns(self, target: str) -> None:
        width = self.tmux(
            ["display-message", "-p", "-t", target, "#{window_width}"]
        ).stdout.strip()
        columns = IdeLayout.columns(int(width)) if width.isdigit() else None
        if columns is None:
            self.tmux(["select-pane", "-t", f"{target}.0"])
            zoomed = self.tmux(
                ["display-message", "-p", "-t", target, "#{window_zoomed_flag}"]
            ).stdout.strip()
            if zoomed != "1":
                self.tmux(["resize-pane", "-Z", "-t", f"{target}.0"])
            return
        sidebar, _, plan = columns
        self.tmux(["resize-pane", "-t", f"{target}.0", "-x", str(sidebar)])
        self.tmux(["resize-pane", "-t", f"{target}.2", "-x", str(plan)])

    def build(self, record: dict[str, Any]) -> None:
        working_dir = record["working_dir"]
        if not Path(working_dir).is_dir():
            raise UsageError(f"Session working directory does not exist: {working_dir}")
        interpreter = (record.get("source") or {}).get("interpreter") or self.python
        handshake = inspect_interpreter(interpreter)
        if handshake["package_version"] != (record.get("source") or {}).get("version"):
            raise UsageError(
                f"Session source version changed at {interpreter}; run source-set again."
            )
        env = self._environment(record)
        sidebar = ["sh", "-c", self._sidebar_command(record)]
        if self.exists():
            created = self.tmux(
                [
                    "new-window",
                    "-d",
                    "-t",
                    self.target,
                    "-n",
                    record["name"],
                    "-P",
                    "-F",
                    "#{window_id}",
                    "-c",
                    working_dir,
                    *env,
                    *sidebar,
                ]
            )
        else:
            created = self.tmux(
                [
                    "new-session",
                    "-d",
                    "-s",
                    self.target,
                    "-n",
                    record["name"],
                    "-P",
                    "-F",
                    "#{window_id}",
                    "-c",
                    working_dir,
                    *env,
                    *sidebar,
                ],
                clean_start=True,
            )
        if created.returncode != 0:
            raise HiveIdeError(created.stderr.strip() or f"Could not create window {record['name']}.")
        target = created.stdout.strip()
        if not target:
            raise HiveIdeError(f"tmux did not return an id for window {record['name']}.")
        for command in (self._agent_command(record), self._plan_command(record)):
            result = self.tmux(
                [
                    "split-window",
                    "-h",
                    "-t",
                    target,
                    "-c",
                    working_dir,
                    *env,
                    "sh",
                    "-c",
                    command,
                ]
            )
            if result.returncode != 0:
                raise HiveIdeError(result.stderr.strip() or f"Could not split window {record['name']}.")
        self._tag(target, record)
        self._apply_columns(target)
        self.tmux(["select-pane", "-t", f"{target}.0"])

    def ensure(self, record: dict[str, Any]) -> bool:
        if record["id"] in self.windows():
            return False
        self.build(record)
        return True

    def rebuild(self, record: dict[str, Any]) -> None:
        existing = self.windows().get(record["id"])
        if existing:
            self.tmux(["kill-window", "-t", existing])
        self.build(record)

    def close(self, session_id: str) -> bool:
        window_id = self.windows().get(session_id)
        if not window_id:
            return False
        return self.tmux(["kill-window", "-t", window_id]).returncode == 0

    def rename(self, session_id: str, display_name: str) -> bool:
        window_id = self.windows().get(session_id)
        if not window_id:
            return False
        return (
            self.tmux(["rename-window", "-t", window_id, display_name]).returncode
            == 0
        )

    def _key_bindings(self) -> dict[str, str | None]:
        settings = self.settings.get("keys") or {}
        bindings = settings.get("bindings")
        if isinstance(bindings, dict):
            return {**DEFAULT_KEYS["bindings"], **bindings}
        return dict(DEFAULT_KEYS["bindings"])

    def bind_keys(self) -> None:
        keys = self._key_bindings()
        prefix = (self.settings.get("keys") or {}).get("prefix")
        base_prefix = self.tmux(
            ["show-option", "-gvq", "@hive_ide_base_prefix"]
        ).stdout.strip()
        if not base_prefix:
            base_prefix = self.tmux(["show-option", "-gv", "prefix"]).stdout.strip()
            if base_prefix:
                self.tmux(
                    ["set-option", "-g", "@hive_ide_base_prefix", base_prefix]
                )
        if prefix:
            self.tmux(["set-option", "-g", "prefix", prefix])
        elif base_prefix:
            self.tmux(["set-option", "-g", "prefix", base_prefix])
        previous_keys = self.tmux(
            ["show-option", "-gvq", "@hive_ide_bound_keys"]
        ).stdout.split()
        for previous in previous_keys:
            self.tmux(["unbind-key", previous])
        self.tmux(["set-option", "-g", "mouse", "on"])
        self.tmux(["set-option", "-g", "focus-events", "on"])
        self.tmux(["set-option", "-s", "extended-keys", "on"])
        self.tmux(["set-option", "-as", "terminal-features", "xterm*:extkeys"])
        new_modal = self._module(
            "newmodal",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
            ],
        )
        if key := keys.get("new"):
            self.tmux(
                [
                    "bind-key",
                    key,
                    "display-popup",
                    "-E",
                    "-w",
                    "52%",
                    "-h",
                    "42%",
                    new_modal,
                ]
            )
        for action, kind in (("agent", "agent"), ("error", "error")):
            key = keys.get(action)
            if not key:
                continue
            popup = self._module(
                "popup",
                [
                    "--kind",
                    kind,
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                ],
            )
            self.tmux(["bind-key", key, "run-shell", "-b", popup])
        for action, kind, width, height in (
            ("card", "card", "64%", "60%"),
            ("help", "keys", "62%", "52%"),
        ):
            key = keys.get(action)
            if not key:
                continue
            info = self._module(
                "info",
                [
                    "--kind",
                    kind,
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--session-id",
                    "#{@hive_ide_session_id}",
                ],
            )
            self.tmux(
                ["bind-key", key, "display-popup", "-E", "-w", width, "-h", height, info]
            )
        if key := keys.get("jump_plan"):
            focus = self._module(
                "cli",
                [
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "current-plan",
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                    "--focus",
                ],
            )
            self.tmux(["bind-key", key, "run-shell", "-b", focus])
        for action, direction in (("next", "next"), ("previous", "prev")):
            key = keys.get(action)
            if not key:
                continue
            command = self._module(
                "nav",
                [
                    "--state-home",
                    str(self.store.home),
                    "--workspace-key",
                    self.store.workspace_key,
                    "--session-id",
                    "#{@hive_ide_session_id}",
                    "--tmux-socket",
                    self.socket,
                    "--direction",
                    direction,
                ],
            )
            self.tmux(["bind-key", key, "run-shell", "-b", command])
        relayout = self._module(
            "relayout",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
                "--mode",
                "snap",
            ],
        )
        if key := keys.get("reset"):
            self.tmux(["bind-key", key, "run-shell", "-b", relayout])
        seen = self._module(
            "seen",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--session-id",
                "#{@hive_ide_session_id}",
            ],
        )
        self.tmux(
            [
                "set-hook",
                "-t",
                self.target,
                "session-window-changed",
                f"run-shell -b {shlex.quote(seen)}",
            ]
        )
        adopt = self._module(
            "relayout",
            [
                "--state-home",
                str(self.store.home),
                "--workspace-key",
                self.store.workspace_key,
                "--tmux-socket",
                self.socket,
                "--mode",
                "adopt",
            ],
        )
        self.tmux(
            [
                "set-hook",
                "-a",
                "-t",
                self.target,
                "session-window-changed",
                f"run-shell -b {shlex.quote(adopt)}",
            ]
        )
        self.tmux(
            [
                "set-hook",
                "-t",
                self.target,
                "client-resized",
                f"run-shell -b {shlex.quote(relayout)}",
            ]
        )
        mobile = f"#{{<:#{{window_width}},{self.SIDEBAR_ZOOM_MAX}}}"
        not_zoomed = "#{!:#{window_zoomed_flag}}"
        focus_condition = f"#{{&&:{mobile},{not_zoomed}}}"
        self.tmux(
            [
                "set-hook",
                "-t",
                self.target,
                "after-select-pane",
                f"if-shell -F '{focus_condition}' 'resize-pane -Z'",
            ]
        )
        sidebar_key = keys.get("sidebar")
        if sidebar_key:
            self.tmux(
                [
                    "bind-key",
                    sidebar_key,
                    "if-shell",
                    "-F",
                    f"#{{<:#{{window_width}},{self.SIDEBAR_ZOOM_MAX}}}",
                    "select-pane -t .0 ; resize-pane -Z",
                    "select-pane -t .0",
                ]
            )
        for action, index in (("chat", "1"), ("plan", "2")):
            key = keys.get(action)
            if not key:
                continue
            self.tmux(
                [
                    "bind-key",
                    key,
                    "if-shell",
                    "-F",
                    f"#{{<:#{{window_width}},{self.SIDEBAR_ZOOM_MAX}}}",
                    f"select-pane -t .{index}",
                    "if-shell -F '#{window_zoomed_flag}' "
                    f"'resize-pane -Z ; select-pane -t .{index}' "
                    f"'select-pane -t .{index}'",
                ]
            )
        bound = sorted({key for key in keys.values() if key})
        self.tmux(
            ["set-option", "-g", "@hive_ide_bound_keys", " ".join(bound)]
        )

    def verify_user_config(self) -> list[str]:
        findings: list[str] = []
        for path in (Path.home() / ".tmux.conf", Path.home() / ".config/tmux/tmux.conf"):
            if not path.exists():
                continue
            try:
                lines = path.read_text(encoding="utf-8").splitlines()
            except OSError:
                continue
            for option in self.DEPENDED_OPTIONS:
                hits = [
                    (index + 1, line.strip())
                    for index, line in enumerate(lines)
                    if re.match(rf"\s*set(-option)?\s+(-\w+\s+)*{option}\b", line)
                ]
                if len(hits) > 1:
                    positions = ", ".join(f"line {line}" for line, _ in hits)
                    findings.append(
                        f"WARN {path.name}: `{option}` set {len(hits)}x ({positions}); "
                        f"last wins: {hits[-1][1]!r}"
                    )
        return findings

    def _record_open_error(
        self, record: dict[str, Any], error: HiveIdeError
    ) -> dict[str, str]:
        detail = str(error)
        self.store.write(
            "errors",
            record["id"],
            {
                "schema_version": SCHEMA_VERSION,
                "workspace_key": self.store.workspace_key,
                "session_id": record["id"],
                "component": "frame:open",
                "summary": f"Could not open session {record['name']}",
                "detail": detail[:8192],
                "retryable": True,
                "recovery": (
                    "Fix the reported session directory or package source, then run "
                    "hive-ide open again."
                ),
                "observed_at": utc_now(),
            },
        )
        return {"session_id": record["id"], "name": record["name"], "error": detail}

    def _clear_open_error(self, record: dict[str, Any]) -> None:
        current = self.store.read("errors", record["id"])
        if current and current.get("component") == "frame:open":
            self.store.delete("errors", record["id"])

    def open(self, *, no_attach: bool = False) -> dict[str, Any]:
        self.require_tmux()
        sessions = self.store.list("sessions")
        if not sessions:
            raise UsageError("This workspace has no sessions. Run hive-ide create first.")
        built: list[str] = []
        failed: list[dict[str, str]] = []
        for record in sessions:
            try:
                if self.ensure(record):
                    built.append(record["id"])
            except HiveIdeError as exc:
                failed.append(self._record_open_error(record, exc))
                continue
            self._clear_open_error(record)
        windows = self.windows()
        if not windows:
            raise UsageError(
                f"No session windows could be opened; {len(failed)} session(s) failed. "
                "Run hive-ide verify and inspect the recorded session errors."
            )
        self.bind_keys()
        first_window = next(
            (windows.get(record["id"]) for record in sessions if windows.get(record["id"])),
            None,
        )
        if first_window:
            self.tmux(["select-window", "-t", first_window])
        if not no_attach:
            os.execvp("tmux", ["tmux", "-L", self.socket, "attach", "-t", self.target])
        return {
            "tmux_socket": self.socket,
            "tmux_session": self.target,
            "built": built,
            "failed": failed,
            "windows": len(windows),
        }
